name: d03

dependencies:
- base >= 4.7 && < 5
- relude

library:
  source-dirs: src

executables:
  d03-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d03
