name:                adventofcode2021
version:             0.1.0.0
github:              "githubuser/haskell"
license:             MIT

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell#readme>

dependencies:
- base >= 4.7 && < 5
- split
- vector
- unordered-containers

executables:
  d01:
    main:                d01.hs
    source-dirs:         d01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d02:
    main:                d02.hs
    source-dirs:         d02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d03:
    main:                d03.hs
    source-dirs:         d03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d04:
    main:                d04.hs
    source-dirs:         d04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d05:
    main:                d05.hs
    source-dirs:         d05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d06:
    main:                d06.hs
    source-dirs:         d06
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d07:
    main:                d07.hs
    source-dirs:         d07
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d08:
    main:                d08.hs
    source-dirs:         d08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d09:
    main:                d09.hs
    source-dirs:         d09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  d10:
    main:                d10.hs
    source-dirs:         d10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
