name: d02

dependencies:
- base >= 4.7 && < 5
- regex-posix

library:
  source-dirs: src

executables:
  d02-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d02
