name: d01

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  d01-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d01
